language: java
jdk:
  - oraclejdk9
before_install:
  - chmod +x gradlew
before_deploy:
  - ./gradlew generatePomFileForMavenPublication
deploy:
  provider: bintray
  file: "descriptor.json"
  user: $BINTRAY_API_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true # to upload artifacts created during the build
  dry-run: false
